services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: parcial2
      MYSQL_USER: marlon
      MYSQL_PASSWORD: marlon123
    volumes:
      - mariadb_data:/var/lib/mysql

  backup:
    image: alpine
    container_name: mariadb_backup
    depends_on:
      - mariadb
    entrypoint: >
      sh -c "
        mysqldump -h mariadb -u root -pexample_password my_database > /backup/$(date +'%Y-%m-%d')_backup.sql
      "
    volumes:
      - mariadb_backup:/backup

  springboot-app:
    image: itzmarlon13/parcial2-electiva:latest
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/parcial2?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mariadb


volumes:
  mariadb_data:
  mariadb_backup:
